// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-projects.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_projects_default = defineTool({
  name: "list_projects",
  title: "Listar projetos",
  description: "Lista os projetos do usu\xE1rio autenticado no NICE OS (nome, dono, status e pr\xF3xima a\xE7\xE3o).",
  inputSchema: {
    limit: z.number().int().optional().describe("M\xE1ximo de projetos a retornar (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "N\xE3o autenticado." }],
        isError: true
      };
    }
    const { data, error } = await supabaseForUser(ctx).from("projects").select("id, name, owner, status, next_action, last_checked_at, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-project.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var create_project_default = defineTool2({
  name: "create_project",
  title: "Criar projeto",
  description: "Cria um novo projeto no NICE OS para o usu\xE1rio autenticado.",
  inputSchema: {
    name: z2.string().trim().min(1).describe("Nome do projeto."),
    owner: z2.string().trim().optional().describe("Respons\xE1vel pelo projeto."),
    status: z2.string().trim().optional().describe("Status inicial (ex.: ativo)."),
    next_action: z2.string().trim().optional().describe("Pr\xF3xima a\xE7\xE3o prevista.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "N\xE3o autenticado." }],
        isError: true
      };
    }
    const { data, error } = await supabaseForUser2(ctx).from("projects").insert({
      user_id: ctx.getUserId(),
      name: input.name,
      owner: input.owner ?? null,
      status: input.status ?? null,
      next_action: input.next_action ?? null
    }).select().single();
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [
        { type: "text", text: `Projeto criado: ${data.name} (${data.id})` }
      ],
      structuredContent: { project: data }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var whoami_default = defineTool3({
  name: "whoami",
  title: "Quem sou eu",
  description: "Retorna o usu\xE1rio autenticado conectado via MCP.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "N\xE3o autenticado." }],
        isError: true
      };
    }
    const info = {
      userId: ctx.getUserId(),
      email: ctx.getUserEmail(),
      clientId: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ibxzyodvtmagnetpyyfz";
var mcp_default = defineMcp({
  name: "nice-os-mcp",
  title: "NICE OS",
  version: "0.1.0",
  instructions: "Ferramentas do NICE OS (Nice Foods). Use `whoami` para verificar a sess\xE3o, `list_projects` para listar os projetos do usu\xE1rio e `create_project` para criar um novo projeto.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_projects_default, create_project_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
